#!/bin/bash

toolchain="robot"

configure=false

for i in "$@" ; do
    if [[ $i == "--configure" ]] ; then
        configure=true
    else
        toolchain=$i
    fi
done

if [ ! -d ".qi" ]; then
    echo "Initializing qibuild"
    qibuild init
fi

if [ ! -d "src/build-$toolchain" ]; then
    configure=true
fi


echo "Build with $toolchain"
cd src
if [ $configure == true ]; then
    qibuild configure -c $toolchain
fi
qibuild make -c $toolchain
cd ..
