#!/bin/bash

echo "Rinobot CodeRelease Setup"
echo ""
if [[ $EUID -eq 0 ]]; then
   echo "This script must not be run as root" 1>&2
   exit 1
fi
echo "Installing required packages"
sudo apt-get install cmake libnss-mdns avahi-discover avahi-utils sshpass unzip python2.7 python-pip
sudo pip install qibuild

toolchain="robot"
if [ "$#" -gt 0 ]; then
    toolchain=$1
fi

if [ ! -d ".qi" ]; then
    echo ""
    echo "Initializing qibuild"
    qibuild init
fi

echo ""
echo "Installing SDK's"
if [ ! -d "sdk" ]; then
    echo "Creating SDK Folder"
    echo "Place a SDK file (ctc-linuxXX-atom-X.X.X.XX.zip) inside the sdk folder and run this script again" 
else
    count=$(ls -l sdk/ | grep .zip | egrep -c '^-')
    if [ $count = 0 ]; then
        echo "No SDK found"
        echo "Place a SDK file (ctc-linuxXX-atom-X.X.X.XX.zip) inside the sdk folder and run this script again" 
        exit 1
    elif [ $count -gt 1 ]; then
        echo "More than one SDK found"
        exit 1
    else
        selected=$(ls -1 sdk/ | grep .zip)
        echo "SDK Found: $selected"
        echo "Extracting"
        unzip -qq -n sdk/$selected -d sdk/
        echo "Creating toolchain $toolchain"
        filename="${selected%.*}"
        qitoolchain create $toolchain sdk/$filename/toolchain.xml
        echo "Adding config"
        qibuild add-config $toolchain -t $toolchain
        echo "Installed as $toolchain"
        echo "You are now able to build and sync to the robot as:"
        echo "./build $toolchain"
        echo "./sync robot-hostname $toolchain"
    fi
fi
